# name: Latest blog post workflow

# on:
#   schedule:
#     # Runs at 00:00 every Sunday (UTC time)
#     - cron: '0 0 * * 0'
#   # Allows you to run this workflow manually from the Actions tab for testing
#   workflow_dispatch: 

# jobs:
#   update-readme-with-blog:
#     name: Update this repo's README with latest blog posts
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
      
#       - name: Pull in medium posts
#         uses: gautamkrishnar/blog-post-workflow@v1
#         with:
#           # Your Medium RSS Feed
#           feed_list: "https://medium.com/feed/@vishalgunjal"
#           max_post_count: 5
#           # Formatting: Bullet point + Title + Link
#           template: "$newline- üìù [$title]($url)"
#           commit_message: "docs: update readme with latest medium posts"



name: Latest blog post workflow

on:
  schedule:
    # Runs once every hour
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Pull in medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@vishalgunjal0287"
          max_post_count: 5
          # The template for the link
          template: "$newline- üìù [$title]($url) ‚Äî $date"
          # üëá FIXED DATE FORMAT
          # 'mmm' = Jan, Feb, Mar (Month Name)
          # 'd'   = 16 (Day)
          # 'yyyy'= 2026 (Year)
          date_format: "mmm d, yyyy"
          commit_message: "docs: update readme with latest medium posts"
