# name: Latest blog post workflow

# on:
#   schedule:
#     # Runs at 00:00 every Sunday (UTC time)
#     - cron: '0 0 * * 0'
#   # Allows you to run this workflow manually from the Actions tab for testing
#   workflow_dispatch: 

# jobs:
#   update-readme-with-blog:
#     name: Update this repo's README with latest blog posts
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
      
#       - name: Pull in medium posts
#         uses: gautamkrishnar/blog-post-workflow@v1
#         with:
#           # Your Medium RSS Feed
#           feed_list: "https://medium.com/feed/@vishalgunjal"
#           max_post_count: 5
#           # Formatting: Bullet point + Title + Link
#           template: "$newline- üìù [$title]($url)"
#           commit_message: "docs: update readme with latest medium posts"



name: Latest blog post workflow

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Medium posts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@vishalgunjal"
          max_post_count: 5
          template: "$newline- üìù [$title]($url) ‚Äî $date"
          date_format: "dd MMM yyyy"
          commit_message: "docs: update README with latest Medium posts"
