name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Pull in medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # Your Feed URL
          feed_list: "https://medium.com/feed/@vishalgunjal"
          max_post_count: 5
          
          # ðŸ‘‡ IMPORTANT: This creates the table row structure
          template: "| [$title]($url) | $date |$newline"
          
          # Date Format
          date_format: "MMM d, yyyy"
          
          commit_message: "docs: update readme with table layout"
