# name: Latest blog post workflow

# on:
#   schedule:
#     # Runs at 00:00 every Sunday (UTC time)
#     - cron: '0 0 * * 0'
#   # Allows you to run this workflow manually from the Actions tab for testing
#   workflow_dispatch: 

# jobs:
#   update-readme-with-blog:
#     name: Update this repo's README with latest blog posts
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
      
#       - name: Pull in medium posts
#         uses: gautamkrishnar/blog-post-workflow@v1
#         with:
#           # Your Medium RSS Feed
#           feed_list: "https://medium.com/feed/@vishalgunjal"
#           max_post_count: 5
#           # Formatting: Bullet point + Title + Link
#           template: "$newline- ğŸ“ [$title]($url)"
#           commit_message: "docs: update readme with latest medium posts"



name: Latest blog post workflow

on:
  schedule:
    # ğŸ‘‡ Runs at minute 0 past every 6th hour (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */5 * * *'
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Pull in medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@vishalgunjal0287"
          max_post_count: 5
          # ğŸ‘‡ Template: Bullet + Icon + Title + Link + " â€” " + Date
          template: "$newline- ğŸ“ [$title]($url) â€” $date"
          # ğŸ‘‡ Date Format: "Jan 16, 2026"
          date_format: "MMM d, yyyy"
          commit_message: "docs: update readme with latest medium posts"
